### ISSUE TITLE
Parser "show bgp all summary" not working on IOSXE

### ISSUE THREAD

**Issue by cisco-allen** [CiscoTestAutomation/genieparser#30]
***The issue was reported by sjhloco***
-------------------

I get the error "msg": "genie_parse: local variable 'cmd' referenced before assignment - Failed to parse command output." when trying to use this parser on an IOSXE device.

```
PLAY [Gather IOSXE BGP outputs] *******************************************************************************************************

TASK [SYS >> Read in parse_genie role] ************************************************************************************************

TASK [NET >> Get IOSXE BGP output] ****************************************************************************************************
ok: [dc1-csr-xnet1]

TASK [SYS >> Parse NXOS BGP output] ***************************************************************************************************
fatal: [dc1-csr-xnet1]: FAILED! => {"msg": "genie_parse: local variable 'cmd' referenced before assignment - Failed to parse command output."}

PLAY RECAP ****************************************************************************************************************************
dc1-csr-xnet1              : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
The playbook works fine with other cmds such as "show bgp all", also confirmed that the parser works fine using "genie parse "show bgp all summary" --testbed-file testbed.yaml --devices "DC1-CSR-XNET1"" against the same device.

Ansible version and playbook book:

```
ansible 2.8.4
  config file = /home/ste/playbooks/chk_device_states/ansible.cfg
  configured module search path = ['/home/ste/virt/ansible_2.8.4/lib/python3.6/site-packages/napalm_ansible/modules']
  ansible python module location = /home/ste/virt/ansible_2.8.4/lib/python3.6/site-packages/ansible
  executable location = /home/ste/virt/ansible_2.8.4/bin/ansible
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```
```
- name: "Gather IOSXE BGP outputs"
  hosts: dc1-csr-xnet1
  connection: local

  tasks:
  - name: SYS >> Read in parse_genie role
    include_role:
      name: clay584.parse_genie

  - name: NET >> Get IOSXE BGP output
    ios_command:
      commands:
        - show bgp all summary
    register: bgp_output

  - name: SYS >> Parse NXOS BGP output
    set_fact:
      pyats_bgp: "{{ bgp_output['stdout'][0] | parse_genie(command='show bgp all summary', os='iosxe') }}"
```
Device output, is on a CSR1000v version 16.06.02:
```
DC1-CSR-XNET1#show bgp all summary 
For address family: VPNv4 Unicast
BGP router identifier 10.10.108.17, local AS number 65002
BGP table version is 6, main routing table version 6
5 network entries using 1280 bytes of memory
5 path entries using 680 bytes of memory
3/3 BGP path/bestpath attribute entries using 888 bytes of memory
2 BGP AS-PATH entries using 48 bytes of memory
0 BGP route-map cache entries using 0 bytes of memory
0 BGP filter-list cache entries using 0 bytes of memory
BGP using 2896 total bytes of memory
BGP activity 5/0 prefixes, 5/0 paths, scan interval 60 secs

Neighbor        V           AS MsgRcvd MsgSent   TblVer  InQ OutQ Up/Down  State/PfxRcd
172.16.101.2    4          901    7199    7269        6    0    0 06:12:04        1
172.16.201.2    4        12076    7199    7269        6    0    0 06:12:06        3
192.168.12.6    4        65001    7422    7267        6    0    0 06:11:55        0
192.168.12.10   4        65001    7396    7242        6    0    0 06:10:36        0
```
Thanks
