### ISSUE TITLE
Genie fails to parse show inventory for stacked devices 

### ISSUE THREAD

**Issue by mdeng10** [CiscoTestAutomation/genieparser#395]
Attempting to use genie to parse `show inventory` for an IOSXE device results in 

```
failed to parse data with genie, genie raised exception: `local variable 'rp_dict' referenced before assignment`
```

The device in question is a stacked device, I've done some testing and found that this error occurs when a module in the inventory has a name that genie doesn't like

i.e. 

```
NAME: "c93xx Stack", DESCR: "c93xx Stack"
PID: C9300-48U         , VID: V02  , SN: FCW88888888

NAME: "Switch 1", DESCR: "C9300-48U"
PID: C9300-48U         , VID: V02  , SN: FCW999999999

NAME: "StackPort1/1", DESCR: "StackPort1/1"
PID: STACK-T1-50CM     , VID: V01  , SN: MOC3333333

NAME: "StackPort1/2", DESCR: "StackPort1/2"
PID: STACK-T1-50CM     , VID: V01  , SN: MOC4444444
```

will result in the error mentioned above, however if the stackports are renamed to the following, no error is returned

```
NAME: "c93xx Stack", DESCR: "c93xx Stack"
PID: C9300-48U         , VID: V02  , SN: FCW88888888

NAME: "Switch 1", DESCR: "C9300-48U"
PID: C9300-48U         , VID: V02  , SN: FCW999999999

NAME: "StackPort1", DESCR: "StackPort1"
PID: STACK-T1-50CM     , VID: V01  , SN: MOC3333333

NAME: "StackPort2", DESCR: "StackPort2"
PID: STACK-T1-50CM     , VID: V01  , SN: MOC4444444
```

and the correct structured data is returned

currently installed versions of genie (`pip freeze | grep genie`)
```
genie==21.1.3
genie.abstract==19.10
genie.conf==19.10
genie.harness==19.10
genie.libs.clean==21.1
genie.libs.conf==21.1
genie.libs.filetransferutils==21.1
genie.libs.health==21.1
genie.libs.ops==21.1
genie.libs.parser==21.1
genie.libs.robot==20.12
genie.libs.sdk==21.1.2
genie.libs.telemetry==19.10
genie.metaparser==19.10
genie.ops==19.10.1
genie.parsergen==19.10
genie.predcore==19.10
genie.telemetry==19.10
genie.trafficgen==19.10
genie.utils==19.10
```

**Comment by kazemy** [comment]
https://wwwin-github.cisco.com/pyATS/support/issues/236

**Comment by kazemy** [comment]
@mdeng10 - Thank you for reaching out. A correction has been implemented and is under review. I will let you know when the review is complete.

**Comment by kazemy** [comment]
@mdeng10 
After more investigation it appears you are not triggering the dedicated parser; in this case the 'show inventory' parser for c9300 platform.
Could you please update your testbed like this in order to use the right parser.
Please make sure 
**platform:c9300 is added under os:'iosxe' 
add custom fields
   abstraction:
      order:[os,platform]**

```
devices:
    "your device":
        type: 'switch'
        os: 'iosxe'
        platform: c9300 #<<< add platform
        tacacs:
            login_prompt: "login:"
            password_prompt: "Password:"
            username: "admin"
        passwords:
            tacacs: lab
            enable: lab
            line: lab
        connections:
            a:
                # Console connection details (for physical device with console port. Not used in gNMI)
                protocol: telnet
                ip: "172.19.72.66"
                port: 2046
            alt:
                # IP address used to VTY to IOS
                protocol : telnet
                ip : "172.19.72.173"
            # gNMI Connection to device (Normally same IP as VTY)
            gnmi:
                # target is IOS IP or FQDN (FQDN Needed for secure connection and for IPv6)
                target: "ADELPHI-42"
                port: 50052
                secure_port: 9339
                # Time to sleep between gNMI operations (sync time):
                op_sleep_time: 3
        custom:   #<<< add custom fields
            abstraction:
                order: [os, platform]

```
