### ISSUE TITLE
Parser for 'traceroute' not found

### ISSUE THREAD

**Issue by assadniang** [CiscoTestAutomation/genieparser#842]
genie==23.8
pyats==23.8

```
    SDWAN-LAN-SW:
        type: router
        os: iosxe
        #platform: sdwan
        #alias: 'uut'
        credentials:
            default:
                username: cisco
                password: cisco
        connections:
            cli:
                protocol: telnet
                ip: 172.30.7.147
```

```
lan_switch.connect(log_stdout=True)
assert lan_switch.connected == True, f'Failed to reconnect to {lan_switch}'
LOGGER.info(f"Successfully connected to {lan_switch}\n")

traceroute = lan_switch.parse('traceroute 192.168.60.3')
```

genie.libs.parser.utils.common.ParserNotFound: Could not find parser for traceroute 192.168.60.3 under ('iosxe', 'router', None)
